name: add new events

on:
  push:
    branches:
      - main

env: 
  TZ: America/Phoenix 
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.1'
      - name: add events
        run: go run main.go calendar
      - name: commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: 'site/content/events'

