name: add new events

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: add events
        run: go run util/main.go
      - name: commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: '_calendar'

