name: post this week's news

on:
  schedule:
    - cron: '0 19 * * 1'
  workflow_dispatch
env: 
  TZ: America/Phoenix 
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      - name: remove old posts
        run: rm _posts/*-this-week.md
      - name: add events
        run: go run util/main.go weekly
      - name: commit
        uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          add: '_posts'

